@api = http://localhost:3000/github

GET {{api}}/2

###
POST {{api}}
Content-Type: application/json

{
    "name": "제3루틴"
}

###
DELETE {{api}}/3

###
GET {{api}}/commit/rineeee

###
Get {{api}}/topRepo